# Zjazd 3, część 1 — NumPy
**Autor:** Marcin Kampa

In [1]:
import numpy as np

In [2]:
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [3]:
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [6]:
# 5. 7 równomiernych punktów od 0 do 1
procenty = np.linspace(0, 1, 7)
print(f"Procenty: {procenty}")

Procenty: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [7]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")


Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [8]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [9]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy:                     0     1    2    3    4    5    6    7    8    9   10   11
# Miesiące:                  Sty  Lut  Mar  Kwi  Maj  Cze  Lip  Sie  Wrz  Paź  Lis  Gru


Sprzedaż w styczniu (indeks 0):

In [11]:
print(miesiace_sprzedaz[0])

120


Sprzedaż w grudniu (ostatni element):

In [12]:
print(miesiace_sprzedaz[-1])

221


Sprzedaż w Q1 (styczeń-marzec, indeksy 0-2):

In [15]:
print(miesiace_sprzedaz[0:3])

[120 135  98]


Sprzedaż w Q4 (październik-grudzień, ostatnie 3):

In [16]:
print(miesiace_sprzedaz[-3:])

[143 198 221]


Sprzedaż co drugi miesiąc (styczeń, marzec, maj...):

In [17]:
print(miesiace_sprzedaz[::2])

[120  98 167 201 156 198]


Sprzedaż od tyłu (grudzień → styczeń):

In [18]:
print(miesiace_sprzedaz[::-2])

[221 143 178 189 142 135]


Sprzedaż 4 produktów w 3 kwartałach

In [19]:
dane = np.array([
    [120, 145, 167],   # Produkt A
    [89,  102, 95],    # Produkt B
    [234, 267, 289],   # Produkt C
    [56,  78,  91],    # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

Sprzedaż Produktu A w Q2 (wiersz 0, kolumna 1)

In [20]:
print(dane[0,1])

145


Cała sprzedaż Produktu C (wiersz 2, wszystkie kolumny):

In [21]:
print(dane[2])

[234 267 289]


Sprzedaż wszystkich produktów w Q1 (wszystkie wiersze, kolumna 0):

In [22]:
print(dane[:,0])

[120  89 234  56]


Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2):

In [24]:
print(dane[1:3,1:3])

[[102  95]
 [267 289]]


# Operacje wektorowe — analiza biznesowa

Produkty w sklepie internetowym

In [25]:
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
         'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']

ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

Zadanie 1: Podstawowe statystyki cenowe

In [26]:
srednia_wartosc = ceny.mean()
indeks_max = ceny.argmax()
indeks_min = ceny.argmin()

print("Średnia cena produktów:", srednia_wartosc)
print("Najdroższy produkt:", nazwy[indeks_max], "w cenie", ceny[indeks_max])
print("Najtańszy produkt:", nazwy[indeks_min], "w cenie", ceny[indeks_min])

Średnia cena produktów: 1171.0
Najdroższy produkt: Laptop w cenie 3499
Najtańszy produkt: Ładowarka w cenie 89


Zadanie 2: Wartość magazynu

In [27]:
wartosci_produktow = ceny * ilosci_magazyn


laczna_wartosc_magazynu = wartosci_produktow.sum()

print("Wartości poszczególnych produktów w magazynie:")
print(wartosci_produktow)

print("\nŁączna wartość całego magazynu wynosi:", laczna_wartosc_magazynu, "zł")

Wartości poszczególnych produktów w magazynie:
[ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]

Łączna wartość całego magazynu wynosi: 549465 zł


Zadanie 3: Analiza cenowa

In [33]:
cena_po_rabacie= ceny * 0.85
print("cena po rabacie wynosi: ",cena_po_rabacie)

cena_Vat = ceny * 1.23
print("cena z VAT wynosi: ",cena_Vat)

ile_powyzej = (ceny > 1000).sum()
print("liczba produktów powyżej 1000zł: ",ile_powyzej)

cena po rabacie wynosi:  [2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
cena z VAT wynosi:  [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
liczba produktów powyżej 1000zł:  4


Zadanie 4: Filtrowanie

In [38]:
nazwy_np = np.array(nazwy)


oceny = oceny_klientow >= 4.5
print("Produkty z oceną >= 4.5:")
print("Nazwy:", nazwy_np[oceny])
print("Ceny:", ceny[oceny])


cena = ceny < 200
print("\nProdukty poniżej 200 zł:")
print("Nazwy:", nazwy_np[cena])
print("Ilości:", ilosci_magazyn[cena])

Produkty z oceną >= 4.5:
Nazwy: ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
Ceny: [3499 2499  349 1499]

Produkty poniżej 200 zł:
Nazwy: ['Ładowarka' 'Mysz']
Ilości: [312 201]


Zadanie 5: Analiza zapasów

In [41]:
nazwy_np = np.array(nazwy)
wartosci_wszystkie = ceny * ilosci_magazyn


ilosc_niski_stan = ilosci_magazyn < 30
nazwy_niski_stan = nazwy_np[ilosc_niski_stan]

wartosc_niski_stan = wartosci_wszystkie[ilosc_niski_stan].sum()

laczna_wartosc = wartosci_wszystkie.sum()
procent_wartosci = (wartosc_niski_stan / laczna_wartosc) * 100

print("Produkty z niskim stanem magazynowym:")
print(nazwy_niski_stan)

print("\nŁączna wartość tych produktów:", wartosc_niski_stan, "zł")
print("Stanowią one", procent_wartosci, "% wartości całego magazynu")

Produkty z niskim stanem magazynowym:
['Laptop' 'Monitor']

Łączna wartość tych produktów: 86962 zł
Stanowią one 15.826667758637946 % wartości całego magazynu


Zadanie 6 (bonus): Analiza korelacji cena–ocena

In [42]:
nazwy_np = np.array(nazwy)


okazja = (oceny_klientow >= 4.5) & (ceny < 1000)

print("Produkty będące okazją:")
print("Nazwy:", nazwy_np[okazja])
print("Ceny:", ceny[okazja])

wysoka_ocena = oceny_klientow >= 4.0
srednia_wysoka = ceny[wysoka_ocena].mean()

niska_ocena = oceny_klientow < 4.0
srednia_niska = ceny[niska_ocena].mean()

print("\nPorównanie średnich cen:")
print("Średnia cena produktów z oceną >= 4.0:", srednia_wysoka, "zł")
print("Średnia cena produktów z oceną < 4.0:", srednia_niska, "zł")

Produkty będące okazją:
Nazwy: ['Słuchawki']
Ceny: [349]

Porównanie średnich cen:
Średnia cena produktów z oceną >= 4.0: 1446.142857142857 zł
Średnia cena produktów z oceną < 4.0: 529.0 zł


# Benchmark — lista vs NumPy

In [43]:
import time

# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start

print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start

start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start

print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start

print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Mnożenie ×2 (1,000,000 elementów) ===
Lista:  76.9 ms
NumPy:  2.8 ms
NumPy jest 28× szybszy!

=== Suma (1,000,000 elementów) ===
Lista:  10.4 ms
NumPy:  0.8 ms
NumPy jest 12× szybszy!

=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista:  57.8 ms
NumPy:  2.9 ms
NumPy jest 20× szybszy!


=== Mnożenie ×2 (1,000,000 elementów) ===
Lista:  76.9 ms
NumPy:  2.8 ms
NumPy jest 28× szybszy!

=== Suma (1,000,000 elementów) ===
Lista:  10.4 ms
NumPy:  0.8 ms
NumPy jest 12× szybszy!

=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista:  57.8 ms
NumPy:  2.9 ms
NumPy jest 20× szybszy!