# Zjazd 3, część 2 — NumPy zaawansowane
**Autor:** Marcin Kampa

In [3]:
import numpy as np

# Broadcasting — zastosowania biznesowe

In [2]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99],    # Produkt A
                  [49.99, 52.99, 47.99],    # Produkt B
                  [14.99, 15.99, 13.99],    # Produkt C
                  [99.99, 104.99, 94.99]])  # Produkt D

sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}")  # (4, 3)

Kształt macierzy: (4, 3)


Zadanie 1a: Stwórz nowy array z cenami podniesionymi o 5% (inflacja). Wyświetl wynik.

In [3]:
print(ceny * 1.05)

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


Zadanie 1b: Stwórz array z cenami po rabacie. Każdy sklep daje inny rabat: Centrum 10%, Galeria 5%, Online 15%.

In [6]:
rabaty = np.array([0.10, 0.05, 0.15])
mnozniki = 1 - rabaty
ceny_po_rabacie = ceny * mnozniki

print("Macierz cen po uwzględnieniu rabatów dla poszczególnych sklepów:")
print(ceny_po_rabacie)

Macierz cen po uwzględnieniu rabatów dla poszczególnych sklepów:
[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


Zadanie 1c: Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną marżę: A=30%, B=40%, C=25%, D=50%.

In [7]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
koszt_zakupu = ceny / (1 + marza)
print("Macierz kosztów zakupu dla każdego produktu (wiersze A, B, C, D):")
print(koszt_zakupu)

Macierz kosztów zakupu dla każdego produktu (wiersze A, B, C, D):
[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


Zadanie 1d: Wyświetl najtańszy sklep dla każdego produktu.

In [8]:
sklepy = np.array(['Centrum', 'Galeria', 'Online'])
indeksy_najtanszych = ceny.argmin(axis=1)
najtansze_sklepy = sklepy[indeksy_najtanszych]
print("Indeksy najtańszych sklepów dla produktów A, B, C, D:")
print(indeksy_najtanszych)

print("\nNazwy najtańszych sklepów:")
print(najtansze_sklepy)

Indeksy najtańszych sklepów dla produktów A, B, C, D:
[2 2 2 2]

Nazwy najtańszych sklepów:
['Online' 'Online' 'Online' 'Online']


 # Reshape i łączenie danych 

Zadanie 2a — Reshape

In [9]:
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


Zadanie 2b — Stacking

In [10]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


Zadanie 2c — Praktyczne

In [11]:
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
sprzedaz_macierz = sprzedaz_flat.reshape(6, 2)
srednia_per_produkt = sprzedaz_macierz.mean(axis=1)
zmiana = sprzedaz_macierz[:, 1] - sprzedaz_macierz[:, 0]

print("Macierz sprzedaży (Produkt x Miesiąc):")
print(sprzedaz_macierz)

print("\nŚrednia sprzedaż dla każdego produktu:")
print(srednia_per_produkt)

print("\nZmiana sprzedaży (Miesiąc 2 - Miesiąc 1):")
print(zmiana)

Macierz sprzedaży (Produkt x Miesiąc):
[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]

Średnia sprzedaż dla każdego produktu:
[150. 225. 215. 170. 240. 225.]

Zmiana sprzedaży (Miesiąc 2 - Miesiąc 1):
[100 150 -70 100 140 -70]


Zadanie 2d — Flatten i concatenate

In [12]:
sprzedaz_wektor = sprzedaz_macierz.flatten()
nowy_miesiac = np.array([235])
sprzedaz_rozszerzona = np.concatenate([sprzedaz_wektor, nowy_miesiac])

print("Wektor po spłaszczeniu (12 miesięcy):")
print(sprzedaz_wektor)

print("\nWektor po dodaniu 13. miesiąca:")
print(sprzedaz_rozszerzona)

Wektor po spłaszczeniu (12 miesięcy):
[100 200 150 300 250 180 120 220 170 310 260 190]

Wektor po dodaniu 13. miesiąca:
[100 200 150 300 250 180 120 220 170 310 260 190 235]


# Ćwiczenie 3: Analiza danych finansowych

Dane

In [4]:
np.random.seed(2026)

# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

Zadanie 3a: Analiza wynagrodzeń

In [21]:
sr_pensje = pensje.mean()
mediana = np.median(pensje)
std_pensje = pensje.std()

print(sr_pensje)
print(mediana)
print(std_pensje)


nazwy_arr = np.array(pracownicy)
powyzej_sredniej = nazwy_arr[pensje > sr_pensje]
print("Osoby zarabiające powyżej średniej: ", powyzej_sredniej)

ponizej_mediany = nazwy_arr[pensje < mediana]
print("Osoby zarabiające poniżej mediany: " ,ponizej_mediany)

rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)

print("Rozstęp (Range): " ,rozstep)
print("Rozstęp międzykwartylowy (IQR): " ,iqr)


6425.0
6050.0
1616.9029037020127
Osoby zarabiające powyżej średniej:  ['Jan' 'Marek' 'Zofia']
Osoby zarabiające poniżej mediany:  ['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstęp (Range):  4900
Rozstęp międzykwartylowy (IQR):  2200.0


Zadanie 3b: System premii (np.where)

In [ ]:
premie = np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))

print("Przyznane premie:")
print(premie)

nowe_wynagrodzenia = pensje + premie

print("\nNowe wynagrodzenia (suma):")
print(nowe_wynagrodzenia)

pracownicy_arr = np.array(pracownicy)
max_premia = premie.max()
maska_najlepszych = (premie == max_premia)
najlepsi = pracownicy_arr[maska_najlepszych]

print("\nOsoby z najwyższą premią:")
print(najlepsi)
print("Kwota najwyższej premii:", max_premia)

Przyznane premie:
[1000    0 2000 1000 2000    0 1000    0]

Nowe wynagrodzenia (suma):
[ 6500  7200  6800 10100  8300  4200  9500  5800]

Osoby z najwyższą premią:
['Ewa' 'Kasia']
Kwota najwyższej premii: 2000


Zadanie 3c: Ranking (argsort)

In [5]:
kolejnosc = np.argsort(pensje)[::-1]


print("Poz.", "Imię", "Pensja", "Staż", sep=" \t ")
print("-" * 40)


for i, idx in enumerate(kolejnosc, 1):
    imie = pracownicy[idx]
    pensja = pensje[idx]
    lata = staz[idx]
    
   
    print(i, imie, pensja, lata, sep=" \t ")

Poz. 	 Imię 	 Pensja 	 Staż
----------------------------------------
1 	 Marek 	 9100 	 15
2 	 Zofia 	 8500 	 12
3 	 Jan 	 7200 	 8
4 	 Kasia 	 6300 	 5
5 	 Tomek 	 5800 	 4
6 	 Anna 	 5500 	 3
7 	 Ewa 	 4800 	 2
8 	 Piotr 	 4200 	 1


Zadanie 3d: Korelacja

In [6]:
kor_staz_pensja = np.corrcoef(staz, pensje)[0, 1]
kor_staz_ocena = np.corrcoef(staz, oceny)[0, 1]


print("Korelacja staż vs pensja:", kor_staz_pensja)
print("Korelacja staż vs ocena:", kor_staz_ocena)
print("-" * 30)


if np.abs(kor_staz_pensja) > np.abs(kor_staz_ocena):
    print("Silniejszy związek występuje między stażem a pensją.")
else:
    print("Silniejszy związek występuje między stażem a oceną.")

Korelacja staż vs pensja: 0.987862864584301
Korelacja staż vs ocena: 0.04198471605953068
------------------------------
Silniejszy związek występuje między stażem a pensją.


Zadanie 3e: Analiza sprzedaży (broadcasting)

In [8]:
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

suma_produkty = przychod.sum(axis=1)
idx_najlepszy_produkt = np.argmax(suma_produkty)
najlepszy_produkt = produkty_nazwy[idx_najlepszy_produkt]


suma_miesiace = przychod.sum(axis=0)
najlepszy_miesiac_numer = np.argmax(suma_miesiace) + 1  


poczatek_suma = przychod[:, :3].sum()
koniec_suma = przychod[:, 3:].sum()

print("Najlepszy produkt:", najlepszy_produkt)
print("Najlepszy miesiąc (numer):", najlepszy_miesiac_numer)
print("-" * 30)
print("Przychód I połowa:", poczatek_suma)
print("Przychód II połowa:", koniec_suma)

if koniec_suma > poczatek_suma:
    print("Trend jest wzrostowy.")
else:
    print("Trend jest spadkowy.")

Najlepszy produkt: Smartfon
Najlepszy miesiąc (numer): 2
------------------------------
Przychód I połowa: 2463950
Przychód II połowa: 2536500
Trend jest wzrostowy.


# Ćwiczenie 4: Generowanie danych

In [11]:
np.random.seed(42)


wiek_raw = np.random.normal(35, 10, 100)

wiek = np.clip(wiek_raw.astype(int), 18, None)


wydatki_raw = np.random.normal(500, 200, 100)

wydatki = np.clip(wydatki_raw, 0, None)


wizyty = np.random.poisson(5, 100)


print("Pierwszych 5 klientów (Wiek | Wydatki | Wizyty):")
print("-" * 45)
for i in range(5):
    print("Klient", i+1, ":", wiek[i], "lat,", wydatki[i], "PLN,", wizyty[i], "wizyt")

Pierwszych 5 klientów (Wiek | Wydatki | Wizyty):
---------------------------------------------
Klient 1 : 39 lat, 216.92585158991716 PLN, 11 wizyt
Klient 2 : 33 lat, 415.8709354469282 PLN, 7 wizyt
Klient 3 : 41 lat, 431.4570966946461 PLN, 3 wizyt
Klient 4 : 50 lat, 339.54454615567624 PLN, 2 wizyt
Klient 5 : 32 lat, 467.74285766679816 PLN, 3 wizyt


In [12]:

print("--- STATYSTYKI: WIEK ---")
print("Średnia:", np.mean(wiek).round(1))
print("Mediana:", np.median(wiek))
print("Odchylenie (std):", np.std(wiek).round(1))
print("Min:", np.min(wiek), "| Max:", np.max(wiek))
print()

kor_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1]
kor_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0, 1]

print("Korelacja Wiek vs Wydatki:", kor_wiek_wydatki.round(3))
print("Korelacja Wizyty vs Wydatki:", kor_wizyty_wydatki.round(3))
print()

sr = wydatki.mean()
sd = wydatki.std()

segmenty = np.where(wydatki > sr + sd, "WYSOKI", 
           np.where(wydatki < sr - sd, "NISKI", "ŚREDNI"))

nazwy_segmentow, ilosc = np.unique(segmenty, return_counts=True)

print("--- SEGMENTACJA WYDATKÓW ---")

for i in range(len(nazwy_segmentow)):
    print("Segment:", nazwy_segmentow[i], "| Liczba klientów:", ilosc[i])

--- STATYSTYKI: WIEK ---
Średnia: 33.6
Mediana: 33.0
Odchylenie (std): 8.6
Min: 18 | Max: 53

Korelacja Wiek vs Wydatki: -0.12
Korelacja Wizyty vs Wydatki: -0.159

--- SEGMENTACJA WYDATKÓW ---
Segment: NISKI | Liczba klientów: 17
Segment: WYSOKI | Liczba klientów: 12
Segment: ŚREDNI | Liczba klientów: 71
